### PR TITLE
Updated to mofo-bootstrap v3.2.0

### LINKED ISSUE #54: Update mofo-bootstrap version to ^3.2.0

### PR DESCRIPTION
**Pull request by mmmavis**
Fixes #54

### CODE REVIEW

**Review by alanmoo — COMMENTED** [review]
I'm not familiar with this site at all but looking at the changes I'm pretty sure you covered the major stuff. Just double check that the elements that have `col-sm-12` are doing what they need to be on xs screens. I believe the sizing class for those was changed to simply `col-##`, but the simple existence of any `col-*` class may be doing what it needs to.

**Comment by mmmavis** [comment]
@alanmoo nice catch, thanks! PR has been updated. Maybe @gvn can give a final check before we hit merge?

**Review by gvn — APPROVED** [review]
Some of the values for margin/padding have been changed in this patch, but if that's intentional then `R+`.

**Comment by mmmavis** [comment]
yay!

**Pull request merged**
